# Syntax highlighting
highlighter:         rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Acbart ePortfolio
tagline:             Computing Education
url:                 http://acbart.github.io/
baseurl:             /

description: Github Pages for acbart
google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

plugins:
  - jekyll-sitemap
