# Syntax highlighting
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               Acbart Site
tagline:             Basic site from Github pages
url:                 http://acbart.github.io/
baseurl:             /
